"""
schemas.py
All Pydantic data models for the Government Citizen Intelligence Platform.
Mode 1 (311 Classifier) and Mode 2 (CJIS RAG) schemas defined here.
Gemini response_schema uses these models directly.
"""

from pydantic import BaseModel, Field
from typing import List, Optional
from enum import Enum


# ============================================================
# MODE 1 — 311 CLASSIFIER SCHEMAS
# ============================================================

class Department(str, Enum):
    """Fixed enum of city/county departments. Gemini must pick from these only."""
    PUBLIC_WORKS = "Public Works"
    TRANSPORTATION = "Transportation"
    PARKS_AND_RECREATION = "Parks and Recreation"
    UTILITIES = "Utilities"
    BUILDING_AND_SAFETY = "Building and Safety"
    ENVIRONMENTAL_SERVICES = "Environmental Services"
    POLICE = "Police"
    FIRE = "Fire"
    HEALTH_SERVICES = "Health Services"
    ANIMAL_CONTROL = "Animal Control"
    HOUSING = "Housing"
    OTHER = "Other"


class UrgencyLevel(str, Enum):
    """Urgency classification with SLA hours."""
    CRITICAL = "CRITICAL"   # Life/safety risk — respond in 2 hours
    HIGH = "HIGH"           # Property damage risk — respond in 24 hours
    MEDIUM = "MEDIUM"       # Quality of life issue — respond in 72 hours
    LOW = "LOW"             # Cosmetic/informational — respond in 7 days


class ActionType(str, Enum):
    """What kind of government action is required."""
    FIELD_INSPECTION = "Field Inspection"
    MAINTENANCE_CREW = "Maintenance Crew Dispatch"
    INVESTIGATION = "Investigation"
    PERMIT_REVIEW = "Permit Review"
    REFERRAL = "Referral to Agency"
    INFORMATION_ONLY = "Information Only"


class WorkOrder(BaseModel):
    """A single department's work item decomposed from a multi-issue complaint."""
    department: Department
    urgency: UrgencyLevel
    sla_hours: int = Field(
        description="Hours within which this department must respond: CRITICAL=2, HIGH=24, MEDIUM=72, LOW=168"
    )
    action_type: ActionType
    issue_description: str = Field(
        description="One sentence describing the specific issue this department must address"
    )


class ClassificationResult(BaseModel):
    """Complete classification result for a 311 citizen request."""
    request_id: Optional[str] = Field(
        default=None,
        description="Set after Gemini call — not generated by Gemini"
    )
    primary_department: Department
    urgency: UrgencyLevel
    sla_hours: int
    work_orders: List[WorkOrder] = Field(
        description="One work order per department involved. Multi-issue complaints produce multiple work orders."
    )
    acknowledgment_letter: str = Field(
        description="Professional 3-4 sentence acknowledgment letter addressed to the citizen. "
                    "Must reference the specific issue reported, the department(s) assigned, and the response timeline."
    )
    classification_confidence: str = Field(
        description="One of: HIGH, MEDIUM, LOW — based on how clearly the complaint maps to departments"
    )


# ============================================================
# MODE 2 — CJIS RAG SCHEMAS
# ============================================================

class CJISCitation(BaseModel):
    """A single policy citation returned with a CJIS answer."""
    section_id: str = Field(
        description="CJIS policy section number, e.g., '5.5.6' or '5.13.1.2'"
    )
    section_title: str = Field(
        description="Title of the section as it appears in the CJIS document"
    )
    policy_version: str = Field(
        description="CJIS version this citation comes from, e.g., 'CJIS Security Policy v6.0'"
    )
    relevance: str = Field(
        description="One sentence explaining why this section is relevant to the question"
    )


class CJISQueryResult(BaseModel):
    """Complete result for a CJIS policy question."""
    query_id: Optional[str] = Field(
        default=None,
        description="Set after Gemini call — not generated by Gemini"
    )
    question: str
    answer: str = Field(
        description="Direct, accurate answer to the question grounded entirely in retrieved CJIS policy chunks. "
                    "Never speculate beyond the retrieved content."
    )
    citations: List[CJISCitation] = Field(
        description="One or more cited sections that directly support the answer. Minimum 1, maximum 5."
    )
    confidence: str = Field(
        description="HIGH if retrieved chunks directly answer the question, MEDIUM if partially, "
                    "LOW if question is outside CJIS scope"
    )
    cannot_answer: bool = Field(
        default=False,
        description="Set True if retrieved chunks do not contain enough information to answer reliably. "
                    "Never hallucinate — return cannot_answer=True instead."
    )


# ============================================================
# SQLITE RECORD SCHEMAS
# ============================================================

class CitizenRequestRecord(BaseModel):
    """Stored in SQLite after each 311 classification."""
    request_id: str
    raw_complaint_text: str
    classification_json: str  # JSON string of ClassificationResult
    created_at: str


class CJISQueryRecord(BaseModel):
    """Stored in SQLite after each CJIS query."""
    query_id: str
    question_text: str
    result_json: str         # JSON string of CJISQueryResult
    chunks_retrieved: int
    created_at: str
